### PR TITLE
enable to copy host files to Docker volume instead of mounting the host directory

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
* Issue: https://discourse.drone.io/t/proposal-add-the-flag-to-drone-exec-command-to-copy-hosts-current-directory-to-the-docker-volume-instead-of-mounting-the-hosts-current-directory/4431

The following pull requests depend on this pull request.

* https://github.com/drone/drone-yaml/pull/41
* https://github.com/drone/drone-cli/pull/123

### CODE REVIEW

**Comment by tboerger** [comment]
Instead of adding this complexity for a corner case you could simply use --local=false?

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback!

At first, drone-cli v0.8.6 has the option "--local" but v1.x doesn't have the option.
Maybe the option was replaced to "--clone" option.

And "--local=false" and "--clone" option mean that drone clones the repository from remote instead of using the local codes, but the pull request enables to test local codes without commiting and pushing changes to the remote.
Especially it is useful for debug. It isn't good to commit and push debug codes to remote for many times.

I think this need isn't a corner case. How do you think?

**Comment by bradrydzewski** [comment]
To enable this feature, we do not need to change the `drone-runtime` or `drone-yaml` libraries.  The cli should be capable of creating a temporary directory, copying the working directory to the temporary directory, and then pass the temporary directory to the drone-yaml as the local volume.

I am not necessarily opposed to optionally copying the project, but since I do not believe it should be part of this library, I am going to close this pull request. Instead we should 1) create an issue at drone/drone-cli to discuss the feature in greater detail and 2) if there is agreement, implement the feature solely in the CLI.

Thanks!

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback!

Okay. I have create the issue.

https://github.com/drone/drone-cli/issues/125

**Pull request closed without merging**
