### PR TITLE
initial attempt at restart policy

### PR DESCRIPTION
**Pull request by jbrockopp**
This is in an effort to address https://discourse.drone.io/t/drone-step-retryable/2065/2.

However, I'm unsure how exactly using the

> built-in Docker retry mechanism

is going to work mainly because the [built-in RestartPolicy](https://github.com/moby/moby/blob/master/api/types/container/host_config.go#L255) for the config only supports the `condition` and `max_attempts` fields from the docker-compose syntax.

I have a feeling we are going to have to implement our own logic for getting the retry logic to adhere to the `delay` and `window` fields. Maybe we could consider using the [restart manager](https://github.com/moby/moby/blob/master/restartmanager/restartmanager.go) under the hood?

### CODE REVIEW

**Comment by bradrydzewski** [comment]
have you tested how the restart impacts log streaming? My worry is that when the container exits it will terminate log tailing and will not resume for subsequent restarts. Can you test it out and document the behavior in this thread? You should be able to test using the command line utility with your sample json file.

(p.s. thanks for the PR)

**Comment by jbrockopp** [comment]
So I modified the `command` section of the `10_restart.json` to contain the below code:

```json
    "command": [
        "echo hello world && echo sleep 10; sleep 10 && echo exit 1; exit 1"
    ],
```

After doing so I observed the following behavior:

```sh
$ drone-runtime samples/10_restart.json
[step_0:0] hello world
[step_0:1] sleep 10
[step_0:2] exit 1
```

While it runs the sleep I ran the below commands:

```sh
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED                  STATUS              PORTS               NAMES
48a1bafbdf6d        alpine:3.6          "/bin/sh -c 'echo he  "   Less than a second ago   Up 2 seconds                            step_0
```

```sh
$ docker logs -f step_0
hello world
sleep 10
exit 1
```

Now what didn't make sense to me was why the container wasn't restarting upon entering the `exit 1` stanza. So after doing some further digging I discovered that it does try restarting it. If you hit the above commands at just the right time, you'll get something like this:

```sh
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED                  STATUS              PORTS               NAMES
48a1bafbdf6d        alpine:3.6          "/bin/sh -c 'echo he  "  2 seconds ago   Restarted (1) Less than a second ago                            step_0
```

```sh
$ docker logs -f step_0
hello world
sleep 10
exit 1
hello world
sleep 10
```

```sh
$ docker inspect step_0 | grep -i -A 2 -B 2 restart
        ],
        "State": {
            "Status": "restarting",
            "Running": true,
            "Paused": false,
--
--
            "Running": true,
            "Paused": false,
            "Restarting": true,
            "OOMKilled": false,
            "Dead": false,
--
--
        "LogPath": "/var/lib/docker/containers/48a1bafbdf6d44cf7d16c51ff8ed1f2c620afa8cd83cb744ebdd6a5bd83cde24/48a1bafbdf6d44cf7d16c51ff8ed1f2c620afa8cd83cb744ebdd6a5bd83cde24-json.log",
        "Name": "/step_0",
        "RestartCount": 1,
        "Driver": "overlay2",
        "Platform": "linux",
--
--
            "NetworkMode": "default",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "on-failure",
                "MaximumRetryCount": 5
```

I'm thinking once it reaches the second `sleep` stanza Docker decides the container isn't responding and just kills it. However I was able to trigger Docker's retry mechanism a different way. I'll lay out what I did for that in the next comment

**Comment by jbrockopp** [comment]
I was able to trigger the built-in Docker retry mechanism by using the above changes in the `command` section of the `10_restart.json` and manually passing the `SIGINT` signal to the process.

Steps to Reproduce:

* Start the process

```sh
$ drone-runtime samples/10_restart.json
[step_0:0] hello world
[step_0:1] sleep 10
```

* Locate the process on the host

```sh
ps -eaf | grep 'samples/10_restart.json'
317864469 33438   945   0 10:52AM ttys002    0:00.00 grep --color samples/10_restart.json
317864469 33433  6221   0 10:52AM ttys006    0:00.01 drone-runtime samples/10_restart.json
```

* Pass the `SIGINT` signal to the process

```sh
kill -s SIGINT 33433
```

* This produces this output from the main process:

```sh
$ drone-runtime samples/10_restart.json
[step_0:0] hello world
[step_0:1] sleep 10
ctrl+c received, terminating process
2018/04/23 10:49:52 Cancelled
```

* Watch Docker implement its native restart policy which eventually leads to the below results:

```sh
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS               NAMES
b5648fcc2366        alpine:3.6          "/bin/sh -c 'echo he  "   57 seconds ago      Exited (1) 2 seconds ago                       step_0
```

```sh
$  docker logs -f step_0
hello world
sleep 10
exit 1
hello world
sleep 10
exit 1
hello world
sleep 10
exit 1
hello world
sleep 10
exit 1
hello world
sleep 10
exit 1
hello world
sleep 10
exit 1
```

**NOTE: If you try to run the `docker logs -f` at the beginning, everytime you hit the `exit 1` stanza, it will stop tailing the logs from the container. This prompts you to have to rerun `docker logs -f`**

```sh
$ docker inspect step_0 | grep -i -A 2 -B 2 restart
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
--
--
        "LogPath": "/var/lib/docker/containers/b5648fcc23663f083d0c5aed580ba25482de07c23d4e3041d2c97d5425109db4/b5648fcc23663f083d0c5aed580ba25482de07c23d4e3041d2c97d5425109db4-json.log",
        "Name": "/step_0",
        "RestartCount": 5,
        "Driver": "overlay2",
        "Platform": "linux",
--
--
            "NetworkMode": "default",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "on-failure",
                "MaximumRetryCount": 5
```

Do you have any thoughts on the above @bradrydzewski ?

**Comment by bradrydzewski** [comment]
> Locate the process on the host
> kill -s SIGINT 33433

Actually, you need to send SIGINT to the container entrypoint (pid 1) in the docker process that is running. It looks like you are canceling the CLI, which is the equivalent of hitting the cancel button in the UI, in which case a restart would not be expected.

You can get the entrypoint pid by running the following command:

```
$ docker top <container>
PID                 USER                TIME                COMMAND
30568               root                0:00                /bin/sh /bin/_drone
30685               root                0:00                go get -v ./...
```

... and then you can kill the process. This will simulate the container exiting unexpectedly and should trigger a restart. Note that Drone interacts directly with the Docker Remote API so there could be functionality built-in to the Docker CLI that is not built into Drone, such as reconnect logic, but hopefully some more testing will help reveal more details.

**Comment by jbrockopp** [comment]
Running from my Mac that did not work. Here is the behavior I observed:

```sh
$ drone-runtime samples/10_restart.json
[step_0:0] hello world
[step_0:1] sleep 10
```

I then ran the `docker top` command:

```sh
$ docker top step_0
PID                 USER                TIME                COMMAND
7241                root                0:00                /bin/sh -c echo hello world && echo sleep 10; sleep 10 && echo exit 1; exit 1
7276                root                0:00                sleep 10
```

I then proceeded to try and kill the process:

```sh
$ kill -s SIGINT 7241
kill: kill 7241 failed: no such process
$ kill -s SIGINT 7276
kill: kill 7276 failed: no such process
```

I then noticed that the user listed under the process was root so I tried with `sudo`:

```sh
$ sudo kill -s SIGINT 7241
kill: 7241 failed: no such process
$ sudo kill -s SIGINT 7276
kill: 7276 failed: no such process
```

I then thought that somehow I was getting the wrong PID from the docker daemon. So I decided to inspect the container and find the PID that way. After rerunning I got this:

```sh
$ docker top step_0
PID                 USER                TIME                COMMAND
7565                root                0:00                /bin/sh -c echo hello world && echo sleep 10; sleep 10 && echo exit 1; exit 1
7596                root                0:00                sleep 10
```

```sh
$ docker inspect -f '{{.State.Pid}}' step_0
7565
```

```sh
$ kill -s SIGINT 7565
kill: kill 7565 failed: no such process
$ sudo kill -s SIGINT 7565
kill: 7565 failed: no such process
```

I got the same result.. so I decided that I'd instead try `exec`ing into the container and killing the process that way. I'll document what I observed with that in my next comment.

**Comment by jbrockopp** [comment]
When I was unable to kill the host PID on my Mac, I thought I'd `exec` into the container to kill the PID.

```sh
$ drone-runtime samples/10_restart.json
[step_0:0] hello world
[step_0:1] sleep 10
```

I then got the PID from inside the container:

```sh
$ docker exec -it step_0 ps -ef
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/sh -c echo hello world && echo sleep 10; sleep 10 &&
    6 root       0:00 sleep 10
   13 root       0:00 ps -ef
```

I then tried to `exec` into the container and kill the PID:

```sh
$ docker exec -it step_0 kill -s SIGINT 1
```

At first I thought it hadn't worked because the sleep process will still running but I noticed that after the sleep process finishes, it will trigger the restart. However it also seemed to reproduce similar behavior we had seen [before](https://github.com/drone/drone-runtime/pull/9#issuecomment-383631512)

```sh
 docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                                    PORTS               NAMES
d8015c8facc6        alpine:3.6          "/bin/sh -c 'echo he…"   11 seconds ago      Restarting (130) Less than a second ago                       step_0
```

```sh
 docker logs -f step_0
hello world
sleep 10
hello world
sleep 10
```

**NOTE: Like before, If you try to run the `docker logs -f` at the beginning, when you hit the container restart, it will stop tailing the logs from the container. This prompts you to have to rerun `docker logs -f`**

```sh
$ docker inspect step_0 | grep -i -A 2 -B 2 restart
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
--
--
        "LogPath": "/var/lib/docker/containers/d8015c8facc6ed30ed705419daada7c028cafd63354ff7a088b228af4a2ae196/d8015c8facc6ed30ed705419daada7c028cafd63354ff7a088b228af4a2ae196-json.log",
        "Name": "/step_0",
        "RestartCount": 1,
        "Driver": "overlay2",
        "Platform": "linux",
--
--
            "NetworkMode": "default",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "on-failure",
                "MaximumRetryCount": 5
```

Just like before it seems to hit the second `sleep` stanza and Docker must decide the container isn't responding and just kills it because Docker does attempt to restart the container only once. I then decided I wanted to try and kill the `sleep` PID that gets spawned instead of the main PID.

```sh
$ drone-runtime samples/10_restart.json
[step_0:0] hello world
[step_0:1] sleep 10
```

```sh
$ docker exec -it step_0 ps -ef
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/sh -c echo hello world && echo sleep 10; sleep 10 &&
    7 root       0:00 sleep 10
   13 root       0:00 ps -ef
```

```sh
$ docker exec -it step_0 kill -s SIGINT 7
```

I noticed that this immediately prompts Docker to attempt to restart the container. However it produces the similar results to above:

```sh
 docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                                    PORTS               NAMES
0d1625d5fab5        alpine:3.6          "/bin/sh -c 'echo he…"   11 seconds ago      Restarting (1) Less than a second ago                       step_0
```

```sh
$ docker logs -f step_0
hello world
sleep 10
hello world
sleep 10
```

```sh
$ docker inspect step_0 | grep -i -A 2 -B 2 restart
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
--
--
        "LogPath": "/var/lib/docker/containers/0d1625d5fab58931d091a33a4209e946210033dbc69fa3c97ee6d7d886d39423/0d1625d5fab58931d091a33a4209e946210033dbc69fa3c97ee6d7d886d39423-json.log",
        "Name": "/step_0",
        "RestartCount": 1,
        "Driver": "overlay2",
        "Platform": "linux",
--
--
            "NetworkMode": "default",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "on-failure",
                "MaximumRetryCount": 5
```

Are these the results you expected @bradrydzewski ?

**Comment by jbrockopp** [comment]
Ping @bradrydzewski so this doesn't go stale

**Comment by bradrydzewski** [comment]
Sorry for the delayed reply ...

I think the issue is that Drone (and Docker) use the `wait` function to wait for the container to exit. When it exits, Drone moves on to the next step. The docker `wait` endpoint does not take restarts into account.

I can reproduce this from the command line. The following exits after a single execution despite the restart policy that is in place:

```text
$ docker run --name="foo" --restart="on-failure:5" alpine /bin/sh -c "echo hello; sleep 30; echo world;exit 255;"
hello
world
$>
```

The `wait` command also exits after the first failure:

```text
$ docker wait foo
255
$>
```

So this current implementation would not achieve the desired result, since the `wait` and `logs` endpoint exit despite the restart policy.

**Comment by jbrockopp** [comment]
@bradrydzewski no worries and thanks for the feedback 👍 

That is as I initially feared. So back to my [original comment](https://github.com/drone/drone-runtime/pull/9#issue-183092343) when I submitted the PR:

> Maybe we could consider using the [restart manager](https://github.com/moby/moby/blob/master/restartmanager/restartmanager.go) under the hood?

What are your thoughts on doing something like this? Or is that introducing more complexity to the codebase than you are looking to implement at this time?

**Comment by jbrockopp** [comment]
Ping @bradrydzewski

**Comment by bradrydzewski** [comment]
The main challenge I see is that the `wait` and `logs` API endpoints return when the container stops. So we would likely need some logic that re-subscribes to these endpoints if we know the container is going to restart (pseudo-code below). The challenge is that we cannot re-subscribe before the container restarts, otherwise the endpoints will immediately exit.

```
var state State
for i:=0; i < step.RestartPolicy.MaxAttempts; i++ {
  	state, err := engine.Wait(ctx, step)
	if err != nil { ... }

	if wait.ExitCode == 0 && wait.OOMKilled == false {
		break
	}
}
```

(note that something similar to above would be required for the log stream)

> Maybe we could consider using the restart manager under the hood?

We might find out that we need more control over the restart process, and that we need to implement some sort of restart manager. If something like this is required, it would ideally be implemented at the Engine level (abstracted away from Docker) because we now have a kubernetes backend and we need to keep feature parity between our Docker and Kubernetes runtimes.

**Comment by jbrockopp** [comment]
@bradrydzewski it sounds like maybe we're trying to implement this feature too soon. Do you agree?

From my standpoint, it looks like this feature would be better suited after 0.9 is released (maybe even 1.0) so we can get a better grasp on the direction of the engine and their interaction with the backends. We hope, we'd see a better option present itself for adding a feature such as this at that time.

**Pull request closed without merging**
