### PR TITLE
Fix issue #31 | Configmap is mounted to home as directory

### PR DESCRIPTION
**Pull request by Shegox**
This PR resolves issue #31.

### CODE REVIEW

**Comment by kevinsimper** [comment]
This is pretty great, how can I test this?

**Comment by tboerger** [comment]
Not sure if it works like expected, but could be an important fix.

**Comment by Shegox** [comment]
> Not sure if it works like expected, but could be an important fix.

I'm quite certain that this should work. Through I was unable to get the runtime to run locally or even build the whole container for testing. If you can test it, that would be awesome.

**Comment by tboerger** [comment]
Ping @bradrydzewski

**Comment by bradrydzewski** [comment]
I think I want to explore a different fix.  I think ideally we would create a single config map and mount to `/var/run/drone`. Then we would copy the .netrc to the `$HOME` directory inside the shell script that is generated for each build.  Mounting the file to under `/root` is not the best approach because the container is not guaranteed to run as the root user.

**Comment by Shegox** [comment]
> I think I want to explore a different fix. I think ideally we would create a single config map and mount to `/var/run/drone`. Then we would copy the .netrc to the `$HOME` directory inside the shell script that is generated for each build. Mounting the file to under `/root` is not the best approach because the container is not guaranteed to run as the root user.

Sounds good, this would also allow to override them if you want to add some custom logic for whatever reason 👍 

A temporary workaround, which works for some images (f.e. node) is overriding $HOME from /root to some other location.

Edit: Do I understand it correctly that you want to default mount it to `/var/run/drone` and then in the `drone-git` plugin copy it to the correct location for only this step? 

What I fear, is if it is done for every step by the drone-runtime it can result in error for stretch containers?

**Comment by bradrydzewski** [comment]
fixed with https://github.com/drone/drone-yaml/commit/1e125e10a9c8c290de8ca6a05428f38ec8be97db

**Pull request closed without merging**
